feat: add level field to spell schema and all spell index examples
5e-bits/docs pull request #33
Opened 2024-04-04 18:58 UTC by BenTracyDotCom

Update docs to reflect PR #411 on 5e-bits/5e-srd-api

2024-04-04 22:45 UTC, bagelbits requested changes

2024-04-04 22:45 UTC, bagelbits commented on yarn.lock
Can you please put this back?

2024-04-04 22:45 UTC, bagelbits commented on openapi.json
> +}
```suggestion
}

```

2024-04-10 15:18 UTC, BenTracyDotCom commented on yarn.lock
Added back sorry!

2024-04-10 15:22 UTC, bagelbits approved these changes

2024-04-10 16:20 UTC, merged